const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion } = require('@whiskeysockets/baileys');
const pino = require('pino');
const qrcode = require('qrcode-terminal');
const fs = require('fs');

// 👑 ADMIN
const ADMIN = '22996959773@s.whatsapp.net';

// 🎯 80 DÉFIS PAR NIVEAU (naturels et engageants)
const defis = {
    facile: [
        "Yo écoute, envoie un vocal où tu chantes ta chanson préférée comme si t'étais en concert 🎤",
        "Mets ta photo de quand t'avais genre 5 ans en photo de profil pendant 2h mdr 👶",
        "Envoie 'Je pense à toi' à 3 contacts au hasard et montre-nous les réactions 😂",
        "Raconte-nous ta pire blague, genre celle que personne trouve drôle 🤡",
        "Fais 20 pompes là maintenant et filme les 5 dernières 💪",
        "Vocal où tu imites 3 animaux différents, on doit deviner 🐶🦁🐸",
        "Parle qu'en verlan pendant les 10 prochains messages frère",
        "Fais un compliment sincère à chaque membre du groupe 💝",
        "Danse sur la première musique qui passe pendant 30 secondes et filme 🕺",
        "30 squats direct, on veut la preuve 🏋️",
        "Selfie avec la pire grimace possible, sois créatif 📸",
        "Chante une chanson mais invente toutes les paroles 🎵",
        "Prends un accent au hasard et parle comme ça pendant 10 minutes 🗣️",
        "Screenshot de ton écran d'accueil, on veut tout voir 👀",
        "Raconte-nous un énorme mensonge et essaie de nous convaincre",
        "Poste une story bizarre sur Insta/Snap pendant 5 minutes",
        "Vocal en chuchotant pendant 30 secondes, dis ce que tu veux",
        "Compte jusqu'à 30 en vocal le plus vite possible sans te tromper",
        "20 jumping jacks tout de suite, allez go 🤸",
        "Envoie un emoji random à 10 contacts et screenshot les réponses",
        "Écris ton prochain message complètement à l'envers",
        "Parle comme un bébé pendant 5 messages minimum",
        "Imite quelqu'un du groupe en vocal, on doit deviner qui",
        "Tiens la planche pendant 45 secondes et filme",
        "Photo de ce que t'as mangé en dernier, ça va être quoi? 🍕",
        "Raconte ton rêve le plus bizarre récemment",
        "Chante un extrait de l'hymne national de ton pays",
        "15 burpees maintenant, vas-y champion",
        "Vocal où tu cries un truc random pendant 5 secondes",
        "Change ton statut WhatsApp en phrase complètement débile pendant 1h",
        "Envoie le meme le plus nul que tu trouves",
        "Parle en rimes pendant 5 messages, montre-nous ton talent",
        "Essaie de faire la roue et filme, on s'en fout si tu réussis pas 😂",
        "Compte à rebours de 20 à 0 en vocal, simple non?",
        "Photo de tes chaussures là maintenant",
        "Raconte-nous une mini histoire d'horreur en 1 minute",
        "10 pompes en diamant si tu peux, sinon normales",
        "Fais du beatbox en vocal pendant 15 secondes",
        "Change ton nom WhatsApp en truc chelou pendant 30 minutes",
        "Balance ta citation ou phrase préférée du moment",
        "Fais des jumping jacks en vocal en même temps que tu parles",
        "Ta meilleure blague de papa, allez vas-y",
        "Selfie avec un animal ou une plante, trouve quelque chose",
        "Compte tous les membres du groupe en chantant",
        "20 squats avec un livre sur la tête, équilibre gros",
        "Vocal avec l'accent exagéré de ta région",
        "Screenshot de tes notifs là maintenant (cache rien de perso)",
        "Raconte un moment gênant de quand t'étais à l'école",
        "15 pompes en applaudissant entre chaque",
        "Chante une chanson Disney, assume",
        "Photo du premier objet rouge autour de toi",
        "Parle comme un pirate pendant 5 messages, arrr! 🏴‍☠️",
        "Fais une pose de yoga chelou et filme",
        "Vocal en parlant super lentement comme un robot cassé",
        "Envoie l'emoji qui te représente le mieux et explique pourquoi",
        "Raconte comment t'as rencontré ton meilleur pote",
        "25 mountain climbers, go go go",
        "Change ta photo de profil en dessin moche pendant 1h",
        "Vocal où tu rappes sur un beat imaginaire",
        "Photo de ton reflet dans un truc (miroir, écran, vitre...)",
        "Compte de 100 à 0 en retirant 7 à chaque fois",
        "Fais une danse TikTok au hasard et filme",
        "Parle en langage super soutenu pendant 8 messages",
        "Screenshot de ta musique préférée en ce moment",
        "Raconte une blague en anglais",
        "15 squats sautés, on veut voir l'explosivité",
        "Vocal en chantant comme à l'opéra, fais-nous rire",
        "Photo du ciel là où tu es maintenant",
        "Raconte ton moment le plus gênant de cette année",
        "Planche latérale 20 secondes de chaque côté",
        "Change ta bio en phrase motivante pendant 12h",
        "Imite une célébrité en vocal, on devine",
        "Photo de la première chose à ta gauche",
        "Dis-nous un rêve que tu veux vraiment réaliser",
        "12 triceps dips sur une chaise",
        "Parle comme un robot pendant 5 messages beep boop",
        "Screenshot du dernier film que t'as regardé",
        "Compte en espagnol jusqu'à 15",
        "High knees pendant 40 secondes, allez",
        "Vocal d'une chanson de ton enfance",
        "Photo de ton espace de travail/bureau"
    ],
    
    moyen: [
        "Bon là c'est sérieux : appelle ton crush et dis juste 'je pensais à toi' puis raccroche 📞😱",
        "Poste une photo/vidéo gênante de toi sur ta story pendant 1h 📱",
        "Envoie 'tu me manques grave' à ton ex et montre-nous la converse après 💔",
        "Karaoké sur une chanson random que quelqu'un choisit, tu filmes tout 🎤",
        "Mange une cuillère de sauce ultra piquante et filme ta réaction 🥵",
        "Quelqu'un du groupe écrit ton statut WhatsApp pendant 24h",
        "Vocal de 2 minutes en accent étranger au choix du groupe 🗣️",
        "Fais le poirier contre un mur pendant 30 secondes 🤸",
        "Supprime l'app que t'utilises le plus pendant 24h (pas WhatsApp) 📵",
        "Parle sans utiliser la lettre 'E' pendant 10 messages, dur non?",
        "Envoie 'faut qu'on parle sérieusement' à 3 contacts et screenshot 😰",
        "Appelle quelqu'un et parle comme un robot pendant 2 minutes 🤖",
        "Le groupe choisit ton nom WhatsApp pendant 2 jours entiers",
        "Vocal où tu racontes ton rêve le plus fou en détails",
        "40 jumping jacks et tu filmes les 15 derniers",
        "Le groupe lit tes 3 derniers messages privés (cache trucs perso)",
        "Photo de toi sans filtre et posting story pendant 2h",
        "Appelle tes parents et parle en langue inventée pendant 1 minute",
        "Mange une combinaison de bouffe bizarre choisie par le groupe",
        "Envoie un vocal 'Coucou' à tes 10 derniers contacts",
        "Change toutes tes photos de profil sur les réseaux pendant 6h",
        "Appelle ton ex et dis que t'as rêvé de lui/elle cette nuit",
        "80 squats en 5 minutes chrono, timer lancé",
        "Quelqu'un poste sur ton Insta story ce qu'il veut (rien de méchant)",
        "Vocal où tu cries pendant 20 secondes non-stop",
        "Bloque ton crush pendant 30 minutes sans expliquer pourquoi",
        "Poste 'Célibataire et disponible' même si c'est faux",
        "Mange un citron entier et filme, on veut la vraie réaction",
        "Appelle un prof/boss et dis bonjour puis raccroche direct",
        "Donne ton mot de passe tel à quelqu'un pendant 5 minutes (change après)",
        "40 pompes sans pause, allez tu peux le faire",
        "Vocal où tu chantes une chanson d'amour à quelqu'un du groupe",
        "Envoie 'tu es spécial(e) pour moi' à 5 contacts random",
        "Poste une vidéo de toi dansant bizarrement",
        "Le groupe choisit ta prochaine publication Insta/Snap",
        "Appelle quelqu'un et pose que des questions pendant 2 minutes",
        "Mange un mélange d'épices/condiments choisi par le groupe",
        "25 burpees sans t'arrêter",
        "Vocal où tu imites 5 personnes différentes, on devine",
        "Change la bio de tous tes réseaux en phrase du groupe pendant 24h",
        "Appelle un numéro inconnu et chante-lui une chanson",
        "Essaie des handstand pushups ou au moins le handstand 5 fois",
        "Quelqu'un texte à ta place pendant 20 minutes",
        "Poste une photo de toi sans maquillage/filtre assumée",
        "Envoie un message gênant à un contact au hasard",
        "150 jumping jacks au total, tu peux faire des pauses",
        "Vocal où tu avoues un secret moyen pas trop grave",
        "Fond d'écran = photo du groupe pendant 1 semaine",
        "Appelle quelqu'un et chante au lieu de parler pendant 1 minute",
        "Mange un truc légèrement périmé (rien de dangereux hein)",
        "Tiens la planche pendant 2 minutes au total (pauses ok)",
        "Montre tes 5 dernières recherches Google au groupe",
        "Poste 'Cherche l'âme sœur' sur ta story",
        "Vocal où tu pleures faussement de manière dramatique",
        "Appelle et raconte une blague nulle super sérieusement",
        "60 squats sautés (tu peux faire des pauses)",
        "Change la langue de ton téléphone pendant 12h",
        "Quelqu'un répond à tes messages à ta place pendant 10 minutes",
        "Poste un throwback ultra embarrassant",
        "Envoie 'Je m'excuse' à 3 personnes sans contexte",
        "Wall sit pendant 3 minutes au total",
        "Imite un animal en vocal pendant 1 minute",
        "Appelle et parle à l'envers (inverse les mots)",
        "Mange un sandwich bizarre genre Nutella-cornichon",
        "80 abdos au total, prends ton temps",
        "Le groupe vote sur ta prochaine story",
        "Envoie un compliment exagéré à 5 contacts",
        "Poste une vidéo de ton talent caché",
        "Appelle et chante joyeux anniversaire au mauvais jour",
        "Fais une pose de yoga difficile pendant 1 minute",
        "Change ta sonnerie en truc embarrassant pendant 3 jours",
        "Quelqu'un choisit ta tenue de demain",
        "Vocal en parlant super vite pendant 1 minute",
        "Poste la photo la plus moche de ta galerie",
        "Appelle et fais semblant d'être une célébrité",
        "40 pompes en diamant",
        "Le groupe pose 1 question, tu réponds 100% honnêtement",
        "Envoie 'pense à moi' à 5 contacts",
        "Poste une citation inspirante avec ta photo la moins flatteuse",
        "Course sur place pendant 3 minutes et filme la dernière minute"
    ],
    
    hard: [
        "Appelle tes parents et dis que t'as fait un tatouage énorme, attends leur réaction 😱",
        "Publie ta photo la plus moche sur TOUS tes réseaux pendant 12h",
        "Déclaration d'amour en vocal de 2 minutes à un membre random du groupe 💕",
        "Mange la combinaison la plus dégueu que le groupe peut imaginer 🤢",
        "Lis tes 10 derniers messages avec ton crush au groupe (cache infos perso) 👀",
        "TikTok ultra gênant en plein public et poste-le 📹",
        "Bloque ton meilleur ami pendant 2h sans prévenir ni expliquer",
        "Appelle ton crush et chante-lui une chanson d'amour complète 🎵",
        "Poste 'Cherche l'amour, voici mon numéro' sur ta story pendant 12h",
        "Vocal de 3 minutes avouant 3 de tes plus gros secrets 🤫",
        "Quelqu'un poste ce qu'il veut sur ton Insta pendant 15 minutes",
        "Appelle ton crush en haut-parleur devant tout le groupe",
        "Envoie 'Je t'aime depuis longtemps' à quelqu'un et screenshot la réaction",
        "Révèle qui dans le groupe tu trouves le/la plus attirant(e)",
        "Poste une vidéo de toi en train de pleurer sur tous tes réseaux",
        "Appelle ton ex et dis que tu veux le/la revoir pour discuter",
        "Le groupe lit TOUS tes messages d'aujourd'hui (cache trucs perso)",
        "Fais une déclaration publique à ton crush sur les réseaux",
        "Donne ton tel déverrouillé à quelqu'un pendant 10 minutes",
        "Envoie un vocal 'vous me manquez' à TOUS tes contacts récents",
        "Le groupe change la bio de tous tes réseaux pendant 3 jours",
        "Appelle tes parents et avoue un énorme secret (faux mais crédible)",
        "Poste 5 photos random de ta galerie sur ta story",
        "Vocal avouant qui est ton crush actuel avec détails",
        "Montre ton historique de navigation de cette semaine au groupe",
        "Envoie un message d'amour à 10 contacts random",
        "Poste 'Ma vie est un mensonge' et explique un truc fake dramatique",
        "Appelle quelqu'un et parle de tes vrais sentiments pour lui/elle",
        "Le groupe peut lire tous tes messages avec 1 personne de ton choix",
        "Révèle ton fantasme le plus secret au groupe (reste approprié)",
        "Poste une vidéo embarrassante de tes archives sur TikTok",
        "Appelle les parents de ton crush et présente-toi",
        "Envoie 'on devrait sortir ensemble' à un contact random",
        "Le groupe pose 5 questions intimes, tu réponds à tout",
        "Poste une confession embarrassante sur ton réseau le plus utilisé",
        "Vocal détaillant tes 3 moments les plus gênants de ta vie",
        "Appelle et déclare ta flamme à quelqu'un choisi par le groupe",
        "Donne ton tel à quelqu'un pendant 30 minutes, il fait ce qu'il veut",
        "Révèle un secret sur quelqu'un que tu connais (rien de méchant)",
        "Poste 'J'ai fait une énorme erreur' sur tous tes réseaux",
        "Envoie un message dramatique à tous tes contacts récents",
        "Appelle ton ex meilleur ami et excuse-toi exagérément",
        "Le groupe crée une fausse conversation gênante pour toi",
        "Poste la liste des 3 personnes que tu as aimées",
        "Vocal racontant ton histoire la plus honteuse",
        "Appelle ton crush et avoue devant témoins",
        "Quelqu'un swipe sur Tinder/app rencontre pour toi pendant 10 minutes",
        "Dis ce que tu penses vraiment de chaque membre du groupe",
        "Poste 'J'ai menti sur quelque chose' et invente un truc fou",
        "Screenshot de 3 conversations privées récentes au groupe",
        "Appelle une personne que tu détestes et fais-lui des compliments",
        "Le groupe lit ton journal intime si t'en as un",
        "Poste la photo/vidéo la plus embarrassante de tes archives",
        "Vocal avouant toutes tes ex-crushes de cette année",
        "Appelle tes parents et raconte un énorme mensonge puis avoue",
        "Quelqu'un répond à tes messages à ta place pendant 1h",
        "Révèle un secret sur toi que personne ne sait",
        "Poste 'Je vais tout changer dans ma vie' avec un faux plan",
        "Envoie un message d'amour à une personne que tu détestais",
        "Appelle ton prof/boss et dis quelque chose de bizarre",
        "Le groupe regarde tes photos cachées/privées",
        "Poste une vidéo chantant une chanson d'amour à quelqu'un de spécifique",
        "Vocal avec une confession que t'as jamais dite à personne",
        "Appelle tes parents et parle de tes sentiments profonds",
        "Quelqu'un peut publier sur tes réseaux pendant 6h",
        "Révèle un fantasme sur quelqu'un que vous connaissez (approprié)",
        "Poste 'J'ai besoin de parler' sur tous tes réseaux puis explique fake truc",
        "Envoie un message dramatique à ton crush",
        "Appelle quelqu'un et crie 'Je t'aime' puis raccroche direct",
        "Le groupe décide d'une grande décision dans ta vie (pas sérieux)",
        "Poste un avant/après embarrassant de toi",
        "Vocal expliquant ton moment le plus dark",
        "Appelle ton ex et demande une seconde chance (blague après si besoin)",
        "Quelqu'un accède à ton cloud/photos pendant 5 minutes",
        "Révèle quelque chose que t'as fait et jamais avoué",
        "Vidéo de toi dansant sur une chanson gênante en public",
        "Envoie 'J'ai réfléchi à nous' à 5 contacts",
        "Appelle tes parents et dis que t'as changé d'orientation (fake)",
        "Le groupe pose des questions ultra intimes, tu réponds complètement",
        "Poste une story 'AMA' et réponds à TOUT pendant 1h",
        "Vocal révélant ce que tu penses vraiment de chaque personne ici"
    ]
};

// ❓ 80 VÉRITÉS PAR NIVEAU
const verites = {
    facile: [
        "Allez, c'est qui ton crush en ce moment et pourquoi lui/elle ? 😍",
        "Dernière fois que t'as menti et c'était sur quoi ? Avoue 🤥",
        "Selon toi, qui est la personne la plus belle dans ce groupe ? 👑",
        "C'est quoi ton rêve le plus fou que tu veux vraiment réaliser ? 💭",
        "Qui tu stalkes le plus sur les réseaux sociaux ? On te juge pas 👀",
        "Ta plus grande peur secrète, c'est quoi ? 😨",
        "Un film ou série que t'adores mais c'est gênant de l'avouer ? 🎬",
        "T'as déjà triché à un exam important ? Sois honnête 📝",
        "Le truc le plus bizarre dans ta chambre en ce moment ? 😳",
        "Quel est le contact le plus bizarre/random dans ton tel ?",
        "T'as déjà fait semblant d'être malade pour sécher ? Quand ?",
        "Quel mensonge t'as dit aujourd'hui ?",
        "Ta chanson guilty pleasure que personne doit savoir ? 🎵",
        "Dernier film qui t'a vraiment fait pleurer ? 😢",
        "Un snack bizarre que t'aimes mais personne comprend ? 🍕",
        "Quelle célébrité tu voudrais rencontrer en vrai ?",
        "Ton plus grand regret de cette année ?",
        "Un truc que tu collectionnes en secret ?",
        "Le surnom le plus gênant qu'on t'a donné ?",
        "L'application que tu utilises le plus par jour ?",
        "Dernier mensonge que t'as dit à tes parents ?",
        "Une personne que tu envies secrètement et pourquoi ?",
        "Un talent caché que peu de gens connaissent ?",
        "Le pire cadeau que t'as jamais reçu ?",
        "La chanson qui te fait automatiquement danser ?",
        "Une phrase ou un mot que tu dis beaucoup trop ?",
        "Ton dernier rêve bizarre dont tu te souviens ?",
        "Un truc que tu fais quand t'es tout seul ?",
        "Un plat que tu détestes mais tout le monde aime ?",
        "Ton excuse préférée pour éviter de faire un truc ?",
        "Ton dernier achat complètement inutile ?",
        "La personne avec qui tu parles le plus ?",
        "Ton souvenir d'enfance le plus gênant ?",
        "Un truc que tu prêtes jamais à personne ?",
        "Ton rituel bizarre avant de dormir ?",
        "Un film que t'as regardé genre 10 fois ?",
        "Le truc qui t'énerve le plus chez les gens ?",
        "Ton plat préféré que tu mangerais tous les jours ?",
        "Dernière fois que t'as eu vraiment peur ?",
        "Une célébrité que tu trouves surcotée ?",
        "Ton endroit préféré pour réfléchir ?",
        "Un truc que tu veux apprendre ?",
        "Ton parfum de glace go-to ?",
        "Dernier vrai compliment que t'as reçu ?",
        "Un truc que tu faisais enfant mais plus maintenant ?",
        "Ton animal préféré et pourquoi ?",
        "Dernière personne avec qui t'as vraiment discuté ?",
        "Ton jeu vidéo préféré si tu joues ?",
        "Un truc qui te fait rire à tous les coups ?",
        "Ton défaut que tu voudrais changer ?",
        "Dernière série que t'as bingewatchée ?",
        "La personne qui t'inspire le plus dans la vie ?",
        "Ton meilleur souvenir de vacances ?",
        "Ce que tu fais pour te détendre vraiment ?",
        "Ton sport préféré à regarder ou pratiquer ?",
        "Dernier livre que t'as lu en entier ?",
        "Un truc que tu aurais voulu faire plus jeune ?",
        "L'emoji que tu utilises le plus ?",
        "La personne à qui tu parles quand tu es triste ?",
        "Ton moment préféré de la journée ?",
        "Un truc que tu pourrais jamais faire ?",
        "Ton plus grand accomplissement cette année ?",
        "Dernier cadeau que t'as offert à quelqu'un ?",
        "Une personne que t'as pas vue depuis longtemps ?",
        