const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion } = require('@whiskeysockets/baileys');
const pino = require('pino');
const qrcode = require('qrcode-terminal');
const fs = require('fs');

// 👑 ADMIN
const ADMIN = '22996959773@s.whatsapp.net';

// 🎯 80 DÉFIS PAR NIVEAU
const defis = {
    facile: [
        "Yo écoute, envoie un vocal où tu chantes ta chanson préférée comme si t'étais en concert 🎤",
        "Mets ta photo de quand t'avais genre 5 ans en photo de profil pendant 2h mdr 👶",
        "Envoie 'Je pense à toi' à 3 contacts au hasard et montre-nous les réactions 😂",
        "Raconte-nous ta pire blague, genre celle que personne trouve drôle 🤡",
        "Fais 20 pompes là maintenant et filme les 5 dernières 💪",
        "Vocal où tu imites 3 animaux différents, on doit deviner 🐶🦁🐸",
        "Parle qu'en verlan pendant les 10 prochains messages frère",
        "Fais un compliment sincère à chaque membre du groupe 💝",
        "Danse sur la première musique qui passe pendant 30 secondes et filme 🕺",
        "30 squats direct, on veut la preuve 🏋️",
        "Selfie avec la pire grimace possible, sois créatif 📸",
        "Chante une chanson mais invente toutes les paroles 🎵",
        "Prends un accent au hasard et parle comme ça pendant 10 minutes 🗣️",
        "Screenshot de ton écran d'accueil, on veut tout voir 👀",
        "Raconte-nous un énorme mensonge et essaie de nous convaincre",
        "Poste une story bizarre sur Insta/Snap pendant 5 minutes",
        "Vocal en chuchotant pendant 30 secondes, dis ce que tu veux",
        "Compte jusqu'à 30 en vocal le plus vite possible sans te tromper",
        "20 jumping jacks tout de suite, allez go 🤸",
        "Envoie un emoji random à 10 contacts et screenshot les réponses",
        "Écris ton prochain message complètement à l'envers",
        "Parle comme un bébé pendant 5 messages minimum",
        "Imite quelqu'un du groupe en vocal, on doit deviner qui",
        "Tiens la planche pendant 45 secondes et filme",
        "Photo de ce que t'as mangé en dernier, ça va être quoi? 🍕",
        "Raconte ton rêve le plus bizarre récemment",
        "Chante un extrait de l'hymne national de ton pays",
        "15 burpees maintenant, vas-y champion",
        "Vocal où tu cries un truc random pendant 5 secondes",
        "Change ton statut WhatsApp en phrase complètement débile pendant 1h",
        "Envoie le meme le plus nul que tu trouves",
        "Parle en rimes pendant 5 messages, montre-nous ton talent",
        "Essaie de faire la roue et filme, on s'en fout si tu réussis pas 😂",
        "Compte à rebours de 20 à 0 en vocal, simple non?",
        "Photo de tes chaussures là maintenant",
        "Raconte-nous une mini histoire d'horreur en 1 minute",
        "10 pompes en diamant si tu peux, sinon normales",
        "Fais du beatbox en vocal pendant 15 secondes",
        "Change ton nom WhatsApp en truc chelou pendant 30 minutes",
        "Balance ta citation ou phrase préférée du moment",
        "Fais des jumping jacks en vocal en même temps que tu parles",
        "Ta meilleure blague de papa, allez vas-y",
        "Selfie avec un animal ou une plante, trouve quelque chose",
        "Compte tous les membres du groupe en chantant",
        "20 squats avec un livre sur la tête, équilibre gros",
        "Vocal avec l'accent exagéré de ta région",
        "Screenshot de tes notifs là maintenant (cache rien de perso)",
        "Raconte un moment gênant de quand t'étais à l'école",
        "15 pompes en applaudissant entre chaque",
        "Chante une chanson Disney, assume",
        "Photo du premier objet rouge autour de toi",
        "Parle comme un pirate pendant 5 messages, arrr! 🏴‍☠️",
        "Fais une pose de yoga chelou et filme",
        "Vocal en parlant super lentement comme un robot cassé",
        "Envoie l'emoji qui te représente le mieux et explique pourquoi",
        "Raconte comment t'as rencontré ton meilleur pote",
        "25 mountain climbers, go go go",
        "Change ta photo de profil en dessin moche pendant 1h",
        "Vocal où tu rappes sur un beat imaginaire",
        "Photo de ton reflet dans un truc (miroir, écran, vitre...)",
        "Compte de 100 à 0 en retirant 7 à chaque fois",
        "Fais une danse TikTok au hasard et filme",
        "Parle en langage super soutenu pendant 8 messages",
        "Screenshot de ta musique préférée en ce moment",
        "Raconte une blague en anglais",
        "15 squats sautés, on veut voir l'explosivité",
        "Vocal en chantant comme à l'opéra, fais-nous rire",
        "Photo du ciel là où tu es maintenant",
        "Raconte ton moment le plus gênant de cette année",
        "Planche latérale 20 secondes de chaque côté",
        "Change ta bio en phrase motivante pendant 12h",
        "Imite une célébrité en vocal, on devine",
        "Photo de la première chose à ta gauche",
        "Dis-nous un rêve que tu veux vraiment réaliser",
        "12 triceps dips sur une chaise",
        "Parle comme un robot pendant 5 messages beep boop",
        "Screenshot du dernier film que t'as regardé",
        "Compte en espagnol jusqu'à 15",
        "High knees pendant 40 secondes, allez",
        "Vocal d'une chanson de ton enfance",
        "Photo de ton espace de travail/bureau"
    ],
    
    moyen: [
        "Bon là c'est sérieux : appelle ton crush et dis juste 'je pensais à toi' puis raccroche 📞😱",
        "Poste une photo/vidéo gênante de toi sur ta story pendant 1h 📱",
        "Envoie 'tu me manques grave' à ton ex et montre-nous la converse après 💔",
        "Karaoké sur une chanson random que quelqu'un choisit, tu filmes tout 🎤",
        "Mange une cuillère de sauce ultra piquante et filme ta réaction 🥵",
        "Quelqu'un du groupe écrit ton statut WhatsApp pendant 24h",
        "Vocal de 2 minutes en accent étranger au choix du groupe 🗣️",
        "Fais le poirier contre un mur pendant 30 secondes 🤸",
        "Supprime l'app que t'utilises le plus pendant 24h (pas WhatsApp) 📵",
        "Parle sans utiliser la lettre 'E' pendant 10 messages, dur non?",
        "Envoie 'faut qu'on parle sérieusement' à 3 contacts et screenshot 😰",
        "Appelle quelqu'un et parle comme un robot pendant 2 minutes 🤖",
        "Le groupe choisit ton nom WhatsApp pendant 2 jours entiers",
        "Vocal où tu racontes ton rêve le plus fou en détails",
        "40 jumping jacks et tu filmes les 15 derniers",
        "Le groupe lit tes 3 derniers messages privés (cache trucs perso)",
        "Photo de toi sans filtre et posting story pendant 2h",
        "Appelle tes parents et parle en langue inventée pendant 1 minute",
        "Mange une combinaison de bouffe bizarre choisie par le groupe",
        "Envoie un vocal 'Coucou' à tes 10 derniers contacts",
        "Change toutes tes photos de profil sur les réseaux pendant 6h",
        "Appelle ton ex et dis que t'as rêvé de lui/elle cette nuit",
        "80 squats en 5 minutes chrono, timer lancé",
        "Quelqu'un poste sur ton Insta story ce qu'il veut (rien de méchant)",
        "Vocal où tu cries pendant 20 secondes non-stop",
        "Bloque ton crush pendant 30 minutes sans expliquer pourquoi",
        "Poste 'Célibataire et disponible' même si c'est faux",
        "Mange un citron entier et filme, on veut la vraie réaction",
        "Appelle un prof/boss et dis bonjour puis raccroche direct",
        "Donne ton mot de passe tel à quelqu'un pendant 5 minutes (change après)",
        "40 pompes sans pause, allez tu peux le faire",
        "Vocal où tu chantes une chanson d'amour à quelqu'un du groupe",
        "Envoie 'tu es spécial(e) pour moi' à 5 contacts random",
        "Poste une vidéo de toi dansant bizarrement",
        "Le groupe choisit ta prochaine publication Insta/Snap",
        "Appelle quelqu'un et pose que des questions pendant 2 minutes",
        "Mange un mélange d'épices/condiments choisi par le groupe",
        "25 burpees sans t'arrêter",
        "Vocal où tu imites 5 personnes différentes, on devine",
        "Change la bio de tous tes réseaux en phrase du groupe pendant 24h",
        "Appelle un numéro inconnu et chante-lui une chanson",
        "Essaie des handstand pushups ou au moins le handstand 5 fois",
        "Quelqu'un texte à ta place pendant 20 minutes",
        "Poste une photo de toi sans maquillage/filtre assumée",
        "Envoie un message gênant à un contact au hasard",
        "150 jumping jacks au total, tu peux faire des pauses",
        "Vocal où tu avoues un secret moyen pas trop grave",
        "Fond d'écran = photo du groupe pendant 1 semaine",
        "Appelle quelqu'un et chante au lieu de parler pendant 1 minute",
        "Mange un truc légèrement périmé (rien de dangereux hein)",
        "Tiens la planche pendant 2 minutes au total (pauses ok)",
        "Montre tes 5 dernières recherches Google au groupe",
        "Poste 'Cherche l'âme sœur' sur ta story",
        "Vocal où tu pleures faussement de manière dramatique",
        "Appelle et raconte une blague nulle super sérieusement",
        "60 squats sautés (tu peux faire des pauses)",
        "Change la langue de ton téléphone pendant 12h",
        "Quelqu'un répond à tes messages à ta place pendant 10 minutes",
        "Poste un throwback ultra embarrassant",
        "Envoie 'Je m'excuse' à 3 personnes sans contexte",
        "Wall sit pendant 3 minutes au total",
        "Imite un animal en vocal pendant 1 minute",
        "Appelle et parle à l'envers (inverse les mots)",
        "Mange un sandwich bizarre genre Nutella-cornichon",
        "80 abdos au total, prends ton temps",
        "Le groupe vote sur ta prochaine story",
        "Envoie un compliment exagéré à 5 contacts",
        "Poste une vidéo de ton talent caché",
        "Appelle et chante joyeux anniversaire au mauvais jour",
        "Fais une pose de yoga difficile pendant 1 minute",
        "Change ta sonnerie en truc embarrassant pendant 3 jours",
        "Quelqu'un choisit ta tenue de demain",
        "Vocal en parlant super vite pendant 1 minute",
        "Poste la photo la plus moche de ta galerie",
        "Appelle et fais semblant d'être une célébrité",
        "40 pompes en diamant",
        "Le groupe pose 1 question, tu réponds 100% honnêtement",
        "Envoie 'pense à moi' à 5 contacts",
        "Poste une citation inspirante avec ta photo la moins flatteuse",
        "Course sur place pendant 3 minutes et filme la dernière minute"
    ],
    
    hard: [
        "Appelle tes parents et dis que t'as fait un tatouage énorme, attends leur réaction 😱",
        "Publie ta photo la plus moche sur TOUS tes réseaux pendant 12h",
        "Déclaration d'amour en vocal de 2 minutes à un membre random du groupe 💕",
        "Mange la combinaison la plus dégueu que le groupe peut imaginer 🤢",
        "Lis tes 10 derniers messages avec ton crush au groupe (cache infos perso) 👀",
        "TikTok ultra gênant en plein public et poste-le 📹",
        "Bloque ton meilleur ami pendant 2h sans prévenir ni expliquer",
        "Appelle ton crush et chante-lui une chanson d'amour complète 🎵",
        "Poste 'Cherche l'amour, voici mon numéro' sur ta story pendant 12h",
        "Vocal de 3 minutes avouant 3 de tes plus gros secrets 🤫",
        "Quelqu'un poste ce qu'il veut sur ton Insta pendant 15 minutes",
        "Appelle ton crush en haut-parleur devant tout le groupe",
        "Envoie 'Je t'aime depuis longtemps' à quelqu'un et screenshot la réaction",
        "Révèle qui dans le groupe tu trouves le/la plus attirant(e)",
        "Poste une vidéo de toi en train de pleurer sur tous tes réseaux",
        "Appelle ton ex et dis que tu veux le/la revoir pour discuter",
        "Le groupe lit TOUS tes messages d'aujourd'hui (cache trucs perso)",
        "Fais une déclaration publique à ton crush sur les réseaux",
        "Donne ton tel déverrouillé à quelqu'un pendant 10 minutes",
        "Envoie un vocal 'vous me manquez' à TOUS tes contacts récents",
        "Le groupe change la bio de tous tes réseaux pendant 3 jours",
        "Appelle tes parents et avoue un énorme secret (faux mais crédible)",
        "Poste 5 photos random de ta galerie sur ta story",
        "Vocal avouant qui est ton crush actuel avec détails",
        "Montre ton historique de navigation de cette semaine au groupe",
        "Envoie un message d'amour à 10 contacts random",
        "Poste 'Ma vie est un mensonge' et explique un truc fake dramatique",
        "Appelle quelqu'un et parle de tes vrais sentiments pour lui/elle",
        "Le groupe peut lire tous tes messages avec 1 personne de ton choix",
        "Révèle ton fantasme le plus secret au groupe (reste approprié)",
        "Poste une vidéo embarrassante de tes archives sur TikTok",
        "Appelle les parents de ton crush et présente-toi",
        "Envoie 'on devrait sortir ensemble' à un contact random",
        "Le groupe pose 5 questions intimes, tu réponds à tout",
        "Poste une confession embarrassante sur ton réseau le plus utilisé",
        "Vocal détaillant tes 3 moments les plus gênants de ta vie",
        "Appelle et déclare ta flamme à quelqu'un choisi par le groupe",
        "Donne ton tel à quelqu'un pendant 30 minutes, il fait ce qu'il veut",
        "Révèle un secret sur quelqu'un que tu connais (rien de méchant)",
        "Poste 'J'ai fait une énorme erreur' sur tous tes réseaux",
        "Envoie un message dramatique à tous tes contacts récents",
        "Appelle ton ex meilleur ami et excuse-toi exagérément",
        "Le groupe crée une fausse conversation gênante pour toi",
        "Poste la liste des 3 personnes que tu as aimées",
        "Vocal racontant ton histoire la plus honteuse",
        "Appelle ton crush et avoue devant témoins",
        "Quelqu'un swipe sur Tinder/app rencontre pour toi pendant 10 minutes",
        "Dis ce que tu penses vraiment de chaque membre du groupe",
        "Poste 'J'ai menti sur quelque chose' et invente un truc fou",
        "Screenshot de 3 conversations privées récentes au groupe",
        "Appelle une personne que tu détestes et fais-lui des compliments",
        "Le groupe lit ton journal intime si t'en as un",
        "Poste la photo/vidéo la plus embarrassante de tes archives",
        "Vocal avouant toutes tes ex-crushes de cette année",
        "Appelle tes parents et raconte un énorme mensonge puis avoue",
        "Quelqu'un répond à tes messages à ta place pendant 1h",
        "Révèle un secret sur toi que personne ne sait",
        "Poste 'Je vais tout changer dans ma vie' avec un faux plan",
        "Envoie un message d'amour à une personne que tu détestais",
        "Appelle ton prof/boss et dis quelque chose de bizarre",
        "Le groupe regarde tes photos cachées/privées",
        "Poste une vidéo chantant une chanson d'amour à quelqu'un de spécifique",
        "Vocal avec une confession que t'as jamais dite à personne",
        "Appelle tes parents et parle de tes sentiments profonds",
        "Quelqu'un peut publier sur tes réseaux pendant 6h",
        "Révèle un fantasme sur quelqu'un que vous connaissez (approprié)",
        "Poste 'J'ai besoin de parler' sur tous tes réseaux puis explique fake truc",
        "Envoie un message dramatique à ton crush",
        "Appelle quelqu'un et crie 'Je t'aime' puis raccroche direct",
        "Le groupe décide d'une grande décision dans ta vie (pas sérieux)",
        "Poste un avant/après embarrassant de toi",
        "Vocal expliquant ton moment le plus dark",
        "Appelle ton ex et demande une seconde chance (blague après si besoin)",
        "Quelqu'un accède à ton cloud/photos pendant 5 minutes",
        "Révèle quelque chose que t'as fait et jamais avoué",
        "Vidéo de toi dansant sur une chanson gênante en public",
        "Envoie 'J'ai réfléchi à nous' à 5 contacts",
        "Appelle tes parents et dis que t'as changé d'orientation (fake)",
        "Le groupe pose des questions ultra intimes, tu réponds complètement",
        "Poste une story 'AMA' et réponds à TOUT pendant 1h",
        "Vocal révélant ce que tu penses vraiment de chaque personne ici"
    ]
};

// ❓ 80 VÉRITÉS PAR NIVEAU
const verites = {
    facile: [
        "Allez c'est qui ton crush en ce moment et pourquoi lui/elle ? 😍",
        "Dernière fois que t'as menti et c'était sur quoi ? Avoue 🤥",
        "Selon toi qui est la personne la plus belle dans ce groupe ? 👑",
        "C'est quoi ton rêve le plus fou que tu veux vraiment réaliser ? 💭",
        "Qui tu stalkes le plus sur les réseaux sociaux ? On te juge pas 👀",
        "Ta plus grande peur secrète c'est quoi ? 😨",
        "Un film ou série que t'adores mais c'est gênant de l'avouer ? 🎬",
        "T'as déjà triché à un exam important ? Sois honnête 📝",
        "Le truc le plus bizarre dans ta chambre en ce moment ? 😳",
        "Quel est le contact le plus bizarre dans ton tel ?",
        "T'as déjà fait semblant d'être malade pour sécher ? Quand ?",
        "Quel mensonge t'as dit aujourd'hui ?",
        "Ta chanson guilty pleasure que personne doit savoir ? 🎵",
        "Dernier film qui t'a vraiment fait pleurer ? 😢",
        "Un snack bizarre que t'aimes mais personne comprend ? 🍕",
        "Quelle célébrité tu voudrais rencontrer en vrai ?",
        "Ton plus grand regret de cette année ?",
        "Un truc que tu collectionnes en secret ?",
        "Le surnom le plus gênant qu'on t'a donné ?",
        "L'application que tu utilises le plus par jour ?",
        "Dernier mensonge que t'as dit à tes parents ?",
        "Une personne que tu envies secrètement et pourquoi ?",
        "Un talent caché que peu de gens connaissent ?",
        "Le pire cadeau que t'as jamais reçu ?",
        "La chanson qui te fait automatiquement danser ?",
        "Une phrase ou un mot que tu dis beaucoup trop ?",
        "Ton dernier rêve bizarre dont tu te souviens ?",
        "Un truc que tu fais quand t'es tout seul ?",
        "Un plat que tu détestes mais tout le monde aime ?",
        "Ton excuse préférée pour éviter de faire un truc ?",
        "Ton dernier achat complètement inutile ?",
        "La personne avec qui tu parles le plus ?",
        "Ton souvenir d'enfance le plus gênant ?",
        "Un truc que tu prêtes jamais à personne ?",
        "Ton rituel bizarre avant de dormir ?",
        "Un film que t'as regardé genre 10 fois ?",
        "Le truc qui t'énerve le plus chez les gens ?",
        "Ton plat préféré que tu mangerais tous les jours ?",
        "Dernière fois que t'as eu vraiment peur ?",
        "Une célébrité que tu trouves surcotée ?",
        "Ton endroit préféré pour réfléchir ?",
        "Un truc que tu veux apprendre ?",
        "Ton parfum de glace préféré ?",
        "Dernier vrai compliment que t'as reçu ?",
        "Un truc que tu faisais enfant mais plus maintenant ?",
        "Ton animal préféré et pourquoi ?",
        "Dernière personne avec qui t'as vraiment discuté ?",
        "Ton jeu vidéo préféré si tu joues ?",
        "Un truc qui te fait rire à tous les coups ?",
        "Ton défaut que tu voudrais changer ?",
        "Dernière série que t'as bingewatchée ?",
        "La personne qui t'inspire le plus dans la vie ?",
        "Ton meilleur souvenir de vacances ?",
        "Ce que tu fais pour te détendre vraiment ?",
        "Ton sport préféré à regarder ou pratiquer ?",
        "Dernier livre que t'as lu en entier ?",
        "Un truc que tu aurais voulu faire plus jeune ?",
        "L'emoji que tu utilises le plus ?",
        "La personne à qui tu parles quand tu es triste ?",
        "Ton moment préféré de la journée ?",
        "Un truc que tu pourrais jamais faire ?",
        "Ton plus grand accomplissement cette année ?",
        "Dernier cadeau que t'as offert à quelqu'un ?",
        "Une personne que t'as pas vue depuis longtemps ?",
        "Le seul plat que tu sais bien cuisiner ?",
        "Un truc que tu aimerais changer chez toi ?",
        "Ton acteur ou actrice préféré(e) ?",
        "Dernière fois que t'as aidé quelqu'un ?",
        "Un truc que tu fais machinalement sans réfléchir ?",
        "Ton objectif principal pour l'année prochaine ?",
        "La personne qui te fait le plus rire ?",
        "Ton style vestimentaire préféré ?",
        "La dernière chose nouvelle que t'as apprise ?",
        "Le truc dont tu es le plus fier/fière ?",
        "Ton parfum ou odeur préféré(e) ?",
        "La personne que tu respectes le plus ?",
        "Ton plus beau souvenir récent ?",
        "Un truc que tu voudrais dire à quelqu'un ?",
        "Où tu te vois dans 5 ans ?",
        "Dernière bonne action que t'as faite ?"
    ],
    
    moyen: [
        "T'as déjà embrassé quelqu'un de ce groupe ? Si oui qui ? Pas de mensonge 💋",
        "Balance ton plus gros secret que t'as jamais dit à personne 🤐",
        "T'as déjà été secrètement amoureux de quelqu'un ici ? Avoue 💘",
        "La pire chose que t'aies jamais faite dans ta vie ? 😈",
        "Ouvre ta galerie scrolle les yeux fermés et montre où tu tombes 📱",
        "T'as déjà trompé quelqu'un ? Contexte complet stp 💔",
        "Le plus gros mensonge que t'as dit à tes parents ? 👨‍👩‍👦",
        "T'as déjà espionné le téléphone de quelqu'un ? Raconte 🕵️",
        "Ta recherche Google la plus bizarre récemment ? 🔍",
        "Si tu devais sortir avec quelqu'un du groupe qui tu choisirais ? 💑",
        "T'as déjà envoyé un message à la mauvaise personne ? Raconte le drame 📨",
        "Ton crush secret dans une autre classe ou cercle d'amis ?",
        "T'as déjà menti sur ton âge ? Quand et pourquoi ? 🎂",
        "Le truc le plus gênant dans ton historique de navigation ?",
        "T'as déjà fait semblant d'aimer quelqu'un ? Pourquoi ?",
        "Une personne que t'as aimée sans qu'elle le sache jamais ?",
        "Un secret que seulement 1 ou 2 personnes connaissent ?",
        "T'as déjà volé quelque chose ? Quoi et où ?",
        "Ton pire date ou rencard ever ? Donne les détails",
        "T'as déjà lu les messages privés de quelqu'un en cachette ?",
        "Un truc embarrassant que tes parents ont découvert ?",
        "T'as déjà menti dans ce jeu avant maintenant ? Sur quoi ?",
        "Une personne dont t'étais jaloux et pourquoi ?",
        "Ton moment le plus gênant en public ?",
        "T'as déjà séché cours ou travail pour un truc fun ?",
        "Un secret sur quelqu'un que tu devrais pas savoir ?",
        "T'as déjà fait un truc juste pour impressionner ?",
        "Une personne que tu évites et la vraie raison ?",
        "Ton mensonge le plus élaboré et longue durée ?",
        "T'as déjà ressenti un truc pour l'ex d'un ami ?",
        "Un truc que t'as fait sous pression du groupe ?",
        "Une personne qui te manque mais tu la contactes pas ?",
        "T'as déjà fait semblant de pas voir quelqu'un ?",
        "Un comportement dont tu as vraiment honte ?",
        "T'as déjà lu le journal intime de quelqu'un ?",
        "Un truc que tu ferais si personne le savait jamais ?",
        "T'as déjà prétendu être malade pour échapper à un truc ?",
        "Une personne que t'as blessée et tu regrettes ?",
        "Une habitude bizarre que tu caches aux autres ?",
        "T'as déjà menti pour protéger quelqu'un d'autre ?",
        "Un truc que t'as fait par vengeance ?",
        "Une personne dont tu parles en mal mais t'es gentil devant ?",
        "T'as déjà fait quelque chose d'illégal mineur ?",
        "Ton plus grand remords dans une relation ?",
        "T'as déjà fait croire que t'étais occupé alors que non ?",
        "Un truc embarrassant dans tes favoris ou signets ?",
        "T'as déjà bloqué quelqu'un puis regretté ?",
        "Une personne que t'as ghostée et pourquoi vraiment ?",
        "Ton mensonge blanc le plus fréquent ?",
        "T'as déjà fouillé dans les affaires de quelqu'un ?",
        "Un truc que t'as fait pour être populaire ?",
        "T'as déjà simulé quelque chose pour éviter un truc ?",
        "Une personne dont t'as brisé le cœur ?",
        "Un secret sur un ami proche que tu gardes ?",
        "T'as déjà révélé un secret qu'on t'avait confié ?",
        "Un truc que tu caches à toute ta famille ?",
        "T'as déjà menti pour éviter un conflit ?",
      "Une personne dont t'as été jaloux du succès ?",
        "Un comportement toxique dont t'es conscient(e) ?",
        "T'as déjà gardé rancune pendant super longtemps ?",
        "Un truc que tu fais différemment devant les autres ?",
        "T'as déjà utilisé quelqu'un pour obtenir un truc ?",
        "Une personne à qui t'as jamais avoué tes vrais sentiments ?",
        "Ton plus gros regret dans une amitié ?",
        "T'as déjà fait semblant d'aimer un cadeau ?",
        "Un truc que tu juges chez les autres mais tu le fais aussi ?",
        "T'as déjà saboté quelque chose pour quelqu'un ?",
        "Une opportunité que t'as laissée passer et tu regrettes ?",
        "T'as déjà menti sur tes sentiments pour quelqu'un ?",
        "Un secret que tu garderas toute ta vie ?",
        "T'as déjà fait un truc juste par jalousie ?",
        "Une personne que t'as jugée trop vite ?",
        "Ton mensonge le plus récent à un proche ?",
        "T'as déjà espionné quelqu'un sur les réseaux avec un faux compte ?",
        "Un truc que tu regrettes d'avoir dit à quelqu'un ?",
        "T'as déjà fait pleurer quelqu'un volontairement ?",
        "Une promesse importante que t'as jamais tenue ?",
        "T'as déjà prétendu être quelqu'un d'autre ?",
        "Un moment où tu savais que tu faisais mal mais tu l'as fait quand même ?"
    ],
    
    hard: [
        "Alors là c'est du lourd : qui dans ce groupe tu trouves vraiment attirant(e) ? Physiquement 😳",
        "Balance un secret VRAIMENT dark de ton passé que personne connaît 💀",
        "T'as déjà eu des pensées bizarres sur quelqu'un ici ? Développe 👀",
        "La chose la plus gênante sexuellement qui t'est arrivée ? (reste approprié) 😱",
        "Montre-nous la dernière personne que t'as stalkée sur Insta et explique pourquoi",
        "Avoue une pensée vraiment sombre que t'as déjà eue 🌑",
        "Ton obsession la plus bizarre que personne connaît ?",
        "Raconte un moment où t'as clairement manipulé quelqu'un",
        "Montre le groupe ou conversation que tu caches le plus 📱",
        "Un truc que t'as fait sous influence que tu regrettes",
        "Une personne dont t'as brisé le cœur exprès ?",
        "Raconte le moment le plus lâche de ta vie",
        "Montre tes comptes fake ou secondaires si t'en as",
        "Un mensonge énorme que tu maintiens depuis longtemps ?",
        "Un rêve bizarre ou inapproprié que t'as eu sur quelqu'un ?",
        "Raconte quand t'as trahi un ami proche",
        "Montre ta liste de personnes bloquées et explique chacune",
        "Un truc illégal que tu ferais s'il y avait aucune conséquence ?",
        "Balance un secret sur une de tes relations passées",
        "Raconte le pire truc que t'as fait par jalousie",
        "Un fantasme que t'assumes pas du tout ? (reste approprié)",
        "La personne ici avec qui tu sortirais vraiment si tu pouvais ?",
        "Ton plus gros secret sur ta vie sentimentale ?",
        "Un truc immoral que t'as fait et jamais avoué ?",
        "Qui dans tes contacts tu aimerais voir disparaître ?",
        "Balance un secret sur ta sexualité (approprié) 🤐",
        "La trahison la plus grave que t'as commise ?",
        "Montre le dernier compte que t'as espionné et pendant combien de temps",
        "Un truc que t'as fait dont t'as vraiment honte ?",
        "Qui tu détestes secrètement dans ton entourage ?",
        "Ton mensonge le plus gros à ton/ta meilleur(e) ami(e) ?",
        "Un secret sur tes parents que personne doit savoir ?",
        "La pire chose que t'as pensée sur quelqu'un ici ?",
        "Un truc sexuel embarrassant de ton passé (approprié)",
        "Qui t'a vraiment brisé le cœur et pourquoi ?",
        "Ton addiction secrète la plus bizarre ?",
        "Un moment où tu t'es senti(e) vraiment mal intentionné(e) ?",
        "Balance un secret sur ton crush actuel",
        "La chose la plus manipulatrice que t'as faite ?",
        "Un message que t'as envoyé et supprimé ? À qui et pourquoi ?",
        "Ton plus gros complexe physique ?",
        "Une personne de ce groupe dont tu es jaloux/jalouse ?",
        "Le truc le plus gênant qu'on pourrait trouver sur ton tel ?",
        "Un fantasme que tu réaliserais si tu pouvais ? (approprié)",
        "Qui tu aimerais embrasser ici si on te forçait ?",
        "Balance un secret sur ta famille que personne sait",
        "La pire pensée que t'as eue sur toi-même ?",
        "Un truc que t'as fait sous pression que tu regrettes ?",
        "Qui dans ta vie tu aimerais revoir et pourquoi ?",
        "Ton plus gros secret sur ton passé amoureux ?",
        "Une chose horrible que t'as dite sur quelqu'un ?",
        "Le mensonge que tu vis depuis le plus longtemps ?",
        "Un truc que tu ferais différemment si tu pouvais recommencer ?",
        "Qui t'a le plus blessé dans ta vie et comment ?",
        "Ton plus gros regret dans une relation ?",
        "Une obsession malsaine que t'as déjà eue ?",
        "Le secret le plus dark de ton cercle d'amis ?",
        "Un truc que tu caches même à ton/ta meilleur(e) ami(e) ?",
        "La personne que tu veux oublier mais tu peux pas ?",
        "Ton comportement le plus toxique en relation ?",
        "Un truc que t'as fait par vengeance et que tu regrettes ?",
        "Qui tu stalkeras toujours même si tu dis que non ?",
        "Ton plus grand complexe psychologique ?",
        "Une personne à qui tu mentiras toujours ?",
        "Le pire truc que t'as fait à quelqu'un qui t'aimait ?",
        "Un secret que tu emporteras dans ta tombe ?",
        "La chose dont tu as le plus honte dans ta vie ?",
        "Qui tu ne pourras jamais pardonner vraiment ?",
        "Ton plus gros mensonge à toi-même ?",
        "Une chose que tu changerais dans ton passé relationnel ?",
        "Le secret le plus lourd que tu portes en ce moment ?",
        "Une personne que tu as utilisée et que tu regrettes ?",
        "Ton plus grand remords dans la vie jusqu'à maintenant ?",
        "Un truc que tu ne diras jamais à personne normalement ?",
        "La vérité sur toi que tu caches le plus aux autres ?",
        "Qui dans ta vie tu aimerais qu'il/elle sache ce que tu ressens ?",
        "Ton secret le plus dangereux à révéler ?",
        "Une chose sur toi que personne croirait si tu la disais ?",
        "Le mensonge que tu voudrais avouer mais tu peux pas ?"
    ]
};

// 👥 DÉFIS DE GROUPE
const defisGroupe = [
    "Ok là tout le monde : screenshot de votre écran d'accueil MAINTENANT sans tricher 📸",
    "VOTE SECRET : Envoyez-moi en DM qui est le/la plus drôle du groupe, je compte",
    "SYNCHRO : Tout le monde change de photo de profil en même temps exact, go go go 🔄",
    "CHAÎNE DE COMPLIMENTS : Chacun complimente la personne suivante de manière originale 💬",
    "SPEED ROUND : Chacun pose une question gênante à la personne d'après ⚡",
    "MODE ROI : Je choisis quelqu'un qui sera roi/reine pendant 10 minutes 🎭",
    "BATTLE DE BLAGUES : Meilleure blague gagne, le groupe vote à la fin 😂",
    "SECRETS ANONYMES : Écrivez un secret, j'en révèle un au hasard 🎲",
    "SCREENSHOT CHALLENGE : Dernier screenshot SANS EXCEPTION, on veut tout voir 📱",
    "KARAOKÉ GÉANT : Tout le monde vocal en chantant la même chanson 🎤",
    "CASCADE DE DÉFIS : Je tire 3 personnes random → Facile/Moyen/Hard 🎯",
    "CONFESSIONS : Envoyez-moi un secret en privé, je partage anonymement 💭",
    "HOT SEAT : Personne random doit répondre à 5 questions du groupe 🔥",
    "BATTLE D'IMITATIONS : Chacun imite un autre membre en vocal/vidéo 🎬",
    "MARATHON FITNESS : 30 squats tous ensemble, je veux les preuves 🏃",
    "DESSIN MYSTÈRE : Dessinez un membre du groupe, postez, on devine qui c'est 🎨",
    "HISTOIRE COLLECTIVE : Chacun écrit une phrase, on crée une histoire de groupe 📝",
    "SHOW DE TALENTS : Montrez un talent caché en 20 secondes max 🎪",
    "VOYANCE : Je prédis l'avenir de 3 personnes random du groupe 🔮",
    "BOMBE À RETARDEMENT : On passe la bombe, qui l'a à la 2ème minute perd 💥",
    "DEVINE LE NOMBRE : 1 à 100, le plus proche gagne un privilège 🎯",
    "IMPRO THÉÂTRE : Jouez une scène ensemble en improvisation totale 🎭",
    "SONDAGE CHAUD : Je pose une question controversée, votez tous 📊",
    "CIRCUS CHALLENGE : Chacun fait un trick physique et le filme 🎪",
    "BATTLE DE MEMES : Créez le meilleur meme sur un membre du groupe 🎨",
    "ANNONCES DRAMATIQUES : Chacun annonce quelque chose de faux mais dramatique 📢",
    "SCÉNARIO GÊNANT : Inventez une histoire embarrassante sur un membre 🎬",
    "DÉFI MINUTE : Chacun un mini-défi en max 60 secondes ⚡",
    "BRAINSTORM FOU : Proposez un projet complètement fou pour le groupe 💡",
    "SPECTACLE IMPROVISÉ : Show de 2 minutes tous ensemble, go 🎪",
    "PHOTO DE GROUPE : Tous la même pose en photo de profil 📸",
    "JEU DE RÔLES : Tout le monde joue un personnage différent pendant 10 min 🎭",
    "ART COLLECTIF : Créez une œuvre ensemble, chacun ajoute un truc 🎨",
    "POÈME DE GROUPE : Écrivez un poème ligne par ligne 📝",
    "PERFORMANCE SYNCHRO : Danse ou chanson synchronisée ensemble 🎪",
    "MISSION IMPOSSIBLE : Mission à accomplir ensemble en 20 minutes 🎯",
    "DÉBAT RANDOM : Débattez d'un sujet au hasard pendant 3 minutes 💬",
    "CLIP VIDÉO : Tournez un mini clip ensemble 🎬",
    "CHALLENGE PHYSIQUE : Relevez un défi sportif tous ensemble 🎪",
    "QUIZ DU GROUPE : Questions sur vous tous, meilleur score gagne 📊"
];

// 🔥 ROASTS
const roasts = [
    "Mec t'es tellement fauché tu regardes les pubs YouTube comme si c'était Netflix 😂",
    "Tu ressembles à une photo prise avec un Nokia 3310 sous l'eau frère",
    "T'es littéralement la raison pour laquelle les shampoings ont des instructions détaillées 📖",
    "Si les excuses étaient des personnes, tu serais une conférence TEDx de 3 heures 🎤",
    "T'es le genre de personne qui perd contre elle-même à Pierre-Papier-Ciseaux ✊",
    "Même Siri fait semblant de pas t'entendre quand tu lui parles 🔇",
    "Tu mets 'Vu' et tu réponds 3 semaines après avec juste 'mdr' 💀",
    "T'es la pub non-skippable de 30 secondes de la vraie vie gros",
    "Tu cours comme si tu essayais de charger une page avec Internet 56k en 1999 🐌",
    "T'es le contact 'Peut-être' dans le téléphone de TOUT LE MONDE",
    "Tu danses comme si ton WiFi laguait en temps réel mdr 📶",
    "T'es tellement en retard tu pourrais organiser ta propre fête surprise passée",
    "Ta vie amoureuse ressemble à mes notes de maths : inexistante",
    "Tu prends plus de temps à te préparer que Rome à se construire frère",
    "T'es littéralement la raison pour laquelle les aliens visitent pas la Terre",
    "Ton sens de l'orientation est aussi bon qu'une boussole cassée",
    "Tu chantes comme si t'essayais de réveiller les morts... pour les re-tuer",
    "T'es tellement lent que même les escargots te dépassent en rigolant 🐌",
    "Ta cuisine est officiellement classée arme de destruction massive",
    "Tu es la preuve vivante que l'évolution peut aller en arrière aussi",
    "Ton humour est sec comme le Sahara en pleine canicule d'août",
    "Tu mens tellement mal que même Pinocchio semble crédible à côté",
    "T'es tellement distrait que tu oublies ce que t'étais en train d'oublier",
    "Ton style vestimentaire crie au secours silencieusement chaque jour",
    "Tu es l'équivalent humain d'un lundi matin pluvieux de novembre",
    "Ta ponctualité est aussi légendaire que les licornes roses",
    "Tu parles tellement que même les perroquets prennent des notes",
    "T'es tellement maladroit que la gravité t'en veut personnellement",
    "Ton talent culinaire ferait pleurer Gordon Ramsay de désespoir pur",
    "T'es la raison pour laquelle les modes d'emploi existent en 47 langues"
];

// 💝 COMPLIMENTS
const compliments = [
    "Franchement t'es tellement cool que même ton ombre refuse de te quitter ☀️",
    "Si t'étais un Pokémon, tu serais un shiny légendaire avec des stats parfaites ⚡",
    "T'es le genre de personne pour qui les chiens abandonneraient leurs maîtres 🐕",
    "Ton sourire pourrait littéralement résoudre la crise énergétique mondiale 😊",
    "T'es tellement cool que même la glace te demande des conseils de vie 🧊",
    "Si la gentillesse était un crime, t'aurais la perpétuité sans libération conditionnelle ❤️",
    "T'es la notification que tout le monde est content de recevoir 📱",
    "Ton énergie positive est plus contagieuse que tous les virus réunis 🌟",
    "T'es le genre de personne qui rend les lundis matins supportables 📅",
    "Si t'étais une chanson, tu serais #1 dans toutes les playlists du monde 🎵",
    "T'es comme du WiFi gratuit et illimité : tout le monde t'adore 📶",
    "Ton rire c'est littéralement la meilleure musique jamais composée 🔔",
    "Tu illumines n'importe quelle pièce juste en y entrant comme une ampoule LED premium 💡",
    "T'es un chef-d'œuvre que même le Louvre voudrait exposer en permanence 🎨",
    "Ta présence améliore n'importe quelle situation instantanément frère",
    "T'es le combo parfait : beauté intérieure + extérieure + personnalité de ouf",
    "Tu rends le monde meilleur juste en existant dedans sérieux 🌍",
    "T'es le genre de personne qui restaure la foi en l'humanité",
    "Ton intelligence n'a d'égale que ta gentillesse et ça c'est rare",
    "T'es l'ami(e) que absolument tout le monde rêve d'avoir 👫",
    "Tu as un don naturel pour rendre les autres heureux autour de toi",
    "T'es la preuve vivante que la perfection existe vraiment dans ce monde",
    "Ta loyauté est plus solide qu'un diamant de 10 carats 💎",
    "T'es inspirant(e) sans même essayer de l'être et ça c'est puissant",
    "Ton cœur est grand comme l'océan Pacifique sérieusement 💙",
    "T'es le genre de personne qui laisse une empreinte positive partout",
    "Tu as cette aura spéciale que très peu de personnes possèdent ✨",
    "T'es l'équilibre parfait entre force et douceur frère/sœur",
    "Ton authenticité est rafraîchissante dans ce monde de faux-semblants",
    "T'es un trésor que ceux qui te connaissent vraiment chérissent 💰"
];

// 🔮 BOULE MAGIQUE
const ball8 = [
    "Oui, absolument et sans le moindre doute possible ! ✅",
    "C'est certain à 100%, je te le garantis perso 💯",
    "Sans l'ombre d'une hésitation, la réponse est clairement OUI !",
    "Les étoiles, planètes et tout le cosmos disent que oui 🔮",
    "Très très probable, presque aussi sûr que le soleil va se lever 🤔",
    "Peut-être bien, peut-être pas... l'avenir est un peu flou là 🤷",
    "Concentre-toi mieux et redemande dans exactement 5 minutes ⏳",
    "Je peux vraiment pas te dire maintenant, c'est compliqué 🤐",
    "Mieux vaut pas trop compter dessus mon ami(e) 😬",
    "Mes sources magiques interdimensionnelles disent clairement NON 🚫",
    "Peu probable malheureusement, désolé de te décevoir comme ça 📉",
    "Non franchement, laisse tomber cette idée maintenant 😕",
    "Absolument PAS, n'y pense même plus une seconde ! ❌",
    "Dans tes rêves peut-être, mais jamais dans la réalité frère 💭",
    "Demande plutôt à ta mère, elle saura mieux que moi 👩",
    "Les signes sont mauvais, vraiment très mauvais là ⚠️",
    "C'est possible mais super improbable statistiquement 📊",
    "Réessaye quand tu seras plus mature mentalement 🧠",
    "La boule magique a crashé en traitant ta question bizarre 💥",
    "La réponse est trop dangereuse à révéler maintenant 🚨"
];

// 💾 SYSTÈME DE DONNÉES
let data = {
    leaderboard: {},
    stats: {},
    sessions: new Map(),
    userProgress: {},
    bannedUsers: [],
    maintenance: false
};

function loadData() {
    try {
        if(fs.existsSync('gamedata.json')) {
            const loaded = JSON.parse(fs.readFileSync('gamedata.json'));
            data.leaderboard = loaded.leaderboard || {};
            data.stats = loaded.stats || {};
            data.userProgress = loaded.userProgress || {};
            data.bannedUsers = loaded.bannedUsers || [];
            data.maintenance = loaded.maintenance || false;
        }
    } catch(e) {
        console.log('⚠️  Erreur chargement données:', e.message);
    }
}

function saveData() {
    try {
        fs.writeFileSync('gamedata.json', JSON.stringify({
            leaderboard: data.leaderboard,
            stats: data.stats,
            userProgress: data.userProgress,
            bannedUsers: data.bannedUsers,
            maintenance: data.maintenance
        }, null, 2));
    } catch(e) {
        console.log('⚠️  Erreur sauvegarde:', e.message);
    }
}

function addPoints(userId, userName, points) {
    if(!data.leaderboard[userId]) {
        data.leaderboard[userId] = {
            name: userName,
            points: 0,
            defis: 0,
            streak: 0,
            lastPlay: Date.now()
        };
    }
    
    const now = Date.now();
    const lastPlay = data.leaderboard[userId].lastPlay;
    const daysDiff = Math.floor((now - lastPlay) / (1000 * 60 * 60 * 24));
    
    if(daysDiff <= 1) {
        data.leaderboard[userId].streak++;
    } else if(daysDiff > 1) {
        data.leaderboard[userId].streak = 1;
    }
    
    data.leaderboard[userId].points += points;
    data.leaderboard[userId].defis++;
    data.leaderboard[userId].lastPlay = now;
    data.leaderboard[userId].name = userName;
    saveData();
}

const rand = arr => arr[Math.floor(Math.random() * arr.length)];

// 🤖 DÉMARRAGE BOT
async function startBot() {
    loadData();
    
    const { state, saveCreds } = await useMultiFileAuthState('auth_session');
    const { version } = await fetchLatestBaileysVersion();
    
    const sock = makeWASocket({
        version,
        auth: state,
        logger: pino({ level: 'silent' }),
        browser: ['Bot Action Vérité', 'Chrome', '1.0.0'],
        printQRInTerminal: false
    });

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect, qr } = update;
        
        if(qr) {
            console.log('\n╔════════════════════════════════╗');
            console.log('║   📱 SCANNE CE QR CODE 📱      ║');
            console.log('╚════════════════════════════════╝\n');
            qrcode.generate(qr, { small: true });
            console.log('\n╔════════════════════════════════╗');
            console.log('║  WhatsApp → Menu → Appareils   ║');
            console.log('║  → Connecter un appareil       ║');
            console.log('╚════════════════════════════════╝\n');
        }
        
        if(connection === 'close') {
            const shouldReconnect = lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut;
            console.log('⚠️  Connexion fermée. Reconnexion:', shouldReconnect);
            if(shouldReconnect) {
                setTimeout(() => startBot(), 3000);
            }
        } else if(connection === 'open') {
            console.log('\n╔════════════════════════════════╗');
            console.log('║  ✅ BOT CONNECTÉ ET PRÊT ! 🎮  ║');
            console.log('╚════════════════════════════════╝\n');
        }
    });

    