const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion } = require('@whiskeysockets/baileys');
const pino = require('pino');
const qrcode = require('qrcode-terminal');
const fs = require('fs');

// 🔐 ADMIN
const ADMIN = '22996959773@s.whatsapp.net';

// 🎯 ACTIONS ULTRA MODERNES POUR JEUNES
const defis = {
    facile: [
        "Envoie un vocal en chantant une chanson TikTok random 🎤",
        "Change ta photo de profil en ton pire selfie pendant 2h 👶",
        "Envoie 'jtm bb' à 5 contacts et screenshot les réponses 💀",
        "Drop ta pire blague de papa dans le groupe 😂",
        "25 pompes et poste les 10 dernières sur story 💪",
        "Imite 3 animaux en vocal, on devine lesquels 🐶",
        "Parle en langage tiktok pendant 10 messages (genre bussin, slay, etc)",
        "Spam de compliments à tout le groupe, personne épargné 💝",
        "Danse sur une trend TikTok et poste 🕺",
        "40 squats sans pause, preuve ou fake 🏋️",
        "Selfie avec la grimace la plus moche, pas de filtre 📸",
        "Invente les paroles d'une chanson connue en chantant 🎵",
        "Parle avec un accent de ouf pendant 15 min 🗣️",
        "Screenshot ton écran d'accueil, aucune triche",
        "Raconte un mensonge, on doit deviner si c'est vrai",
        "Story bizarre sur Snap pendant 10 min",
        "Vocal en chuchotant comme un psychopathe",
        "Compte jusqu'à 50 en vocal le plus vite possible",
        "30 jumping jacks, on veut la vidéo",
        "Envoie un emoji random à 10 personnes sans contexte",
        "Écris un message complet à l'envers, aucune aide",
        "Parle comme un bébé pendant 5 messages genre 'jwé pa fair sa'",
        "Imite quelqu'un du groupe en vocal, on devine qui",
        "Planche 1 minute, chrono obligatoire",
        "Photo de ton dernier repas dégueulasse",
        "Raconte le rêve le plus bizarre que t'as fait",
        "Chante l'hymne national version opera dramatique",
        "20 burpees, vidéo ou ça compte pas",
        "Vocal en mode cri primal pendant 10 secondes",
        "Change ton statut en phrase débile pendant 2h",
        "Balance le meme le plus random de ta galerie",
        "Parle en rimes pendant 5 messages minimum",
        "Fais la roue, vidéo obligatoire sinon fake",
        "Compte à rebours de 30 en vocal dramatique",
        "Photo de tes chaussures les plus moches",
        "Raconte une histoire d'horreur en 1 min chrono",
        "15 pompes en position diamant, pas de cheat",
        "Beatbox pendant 20 secondes, on évalue après",
        "Change ton nom WhatsApp en truc random 1h",
        "Vocal où tu imites une célébrité, on devine qui"
    ],
    
    moyen: [
        "Appelle ton crush et dis 'je pense trop à toi' puis raccroche direct 📞",
        "Story Insta embarrassante pendant 2h, pas de suppression 📱",
        "Envoie 'tu me manques grave' à ton ex et screenshot 💔",
        "Karaoké sur une chanson gênante et poste la vidéo 🎤",
        "Mange une cuillère de sauce piquante et filme ta réaction 🥵",
        "Laisse quelqu'un écrire ton statut WhatsApp pendant 24h",
        "Vocal 2 min en accent de bled total 🗣️",
        "Poirier contre le mur pendant 1 minute 🤸",
        "Supprime ton app préférée (TikTok/Snap/Insta) pendant 24h 📵",
        "Parle sans utiliser la lettre 'E' pendant 15 min",
        "Envoie 'on doit parler sérieusement' à 5 contacts sans expliquer 😰",
        "Appelle quelqu'un et parle comme un robot pendant 3 min 🤖",
        "Le groupe change ton nom WhatsApp pour 2 jours",
        "Vocal où tu racontes ton cauchemar le plus chelou",
        "50 jumping jacks et filme les 20 derniers",
        "Le groupe lit tes 5 derniers messages privés avec n'importe qui",
        "Poste ta pire photo en story pendant 3h",
        "Appelle tes parents et parle en langue inventée pendant 1 min",
        "Mange une combinaison dégueulasse choisie par le groupe",
        "Envoie un message vocal 'salut' à TOUS tes contacts",
        "Change toutes tes photos de profil sur tous les réseaux pendant 12h",
        "Appelle ton ex et dis que tu as rêvé de lui/elle",
        "100 squats en moins de 5 minutes, chrono lancé",
        "Laisse quelqu'un poster sur ton Insta story",
        "Vocal où tu cries comme un dingue pendant 30 secondes",
        "Bloque ton crush pendant 1h sans dire pourquoi",
        "Poste 'je suis célibataire et je cherche' en story même si c'est faux",
        "Mange un citron entier et filme ta tronche",
        "Appelle un prof/boss juste pour dire bonjour puis raccroche",
        "Donne ton mot de passe de tel à quelqu'un pendant 10 min",
        "50 pompes d'affilée sans pause, preuve vidéo",
        "Chante une chanson d'amour en vocal à quelqu'un du groupe",
        "Envoie 'tu es spécial(e) pour moi' à 10 contacts",
        "Vidéo de toi en train de danser comme un débile",
        "Le groupe choisit ta prochaine publication sur les réseaux",
        "Appelle quelqu'un et parle qu'en posant des questions pendant 2 min",
        "Mange un mélange random de condiments",
        "30 burpees sans aucune pause",
        "Vocal où tu imites 5 personnes différentes d'affilée",
        "Change ta bio sur tous tes réseaux, le groupe décide, 48h"
    ],
    
    hard: [
        "Appelle tes parents et dis que t'as fait un énorme tatouage 😱",
        "Poste ta photo la plus moche sur TOUS les réseaux pendant 24h",
        "Déclaration d'amour vocale de 2 min à un membre random du groupe 💕",
        "Mange le truc le plus dégueulasse que le groupe choisit 🤢",
        "Lis tes 20 derniers messages avec ton crush devant tout le monde 👀",
        "TikTok ultra embarrassant en public et poste-le 📹",
        "Bloque ton meilleur ami pendant 3h sans prévenir",
        "Appelle ton crush et chante-lui une chanson d'amour complète 🎵",
        "Story 'Je cherche l'amour + ton numéro' pendant 24h",
        "Vocal 5 min où tu avoues tes 5 plus gros secrets 🤫",
        "Laisse quelqu'un poster ce qu'il veut sur ton Insta pendant 30 min",
        "Appelle ton crush et mets le haut-parleur devant tout le groupe",
        "Envoie 'je t'aime depuis longtemps' à quelqu'un et screenshot",
        "Révèle qui dans le groupe tu trouves le/la plus attirant(e)",
        "Vidéo de toi en train de pleurer sur tous les réseaux",
        "Appelle ton ex et dis que tu veux le/la revoir",
        "Le groupe lit TOUS tes messages d'aujourd'hui",
        "Déclaration publique à ton crush sur les réseaux sociaux",
        "Donne ton tel déverrouillé à quelqu'un pendant 15 min",
        "Envoie un vocal 'vous me manquez' à TOUS tes contacts",
        "Change ta bio sur tous les réseaux, le groupe décide, pendant 1 semaine",
        "Appelle tes parents et avoue un secret énorme (faux après)",
        "Poste 10 photos random de ta galerie en story",
        "Vocal où tu avoues ton crush actuel avec tous les détails",
        "Le groupe peut voir ton historique de navigation de la semaine",
        "Envoie un message d'amour à 20 contacts random",
        "Poste 'Ma vie est un mensonge' et explique pourquoi",
        "Appelle quelqu'un et parle de tes vrais sentiments",
        "Le groupe lit tous tes messages privés avec une personne",
        "Révèle ton fantasme le plus secret devant tout le groupe",
        "Vidéo embarrassante de tes archives sur TikTok",
        "Appelle les parents de ton crush et présente-toi",
        "Envoie 'on devrait sortir ensemble' à un contact random",
        "Le groupe pose 10 questions, tu réponds à TOUT honnêtement",
        "Confession embarrassante sur Facebook public",
        "Vocal où tu racontes tous tes moments les plus gênants",
        "Appelle et déclare ta flamme à quelqu'un que le groupe choisit",
        "Laisse quelqu'un contrôler ton tel pendant 1h complète",
        "Révèle un secret sur quelqu'un d'autre que tu connais",
        "Vocal confession de quelque chose que t'as jamais dit à personne"
    ]
};

// ❓ VÉRITÉS MODERNES (40 par niveau)
const verites = {
    facile: [
        "C'est qui ton crush en ce moment, balance le nom 😍",
        "Dernière fois que t'as menti et c'était sur quoi ? 🤥",
        "Qui est la personne la plus stylée du groupe selon toi ? 👑",
        "C'est quoi ton rêve le plus ouf que tu veux réaliser ? 💭",
        "Qui stalkes-tu en boucle sur les réseaux avoue 👀",
        "Ta plus grande peur secrète c'est quoi ? 😨",
        "Film ou série que tu adores mais c'est un peu honteux ? 🎬",
        "T'as déjà triché à un exam important ? Balance 📝",
        "Le truc le plus gênant dans ta chambre là maintenant ? 😳",
        "C'est qui le contact le plus bizarre de ton tel ?",
        "T'as déjà fake d'être malade pour sécher ? 🤒",
        "C'est quoi le dernier mensonge que t'as dit aujourd'hui ?",
        "Ta chanson guilty pleasure que personne connaît ? 🎵",
        "Dernier film qui t'a fait chialer comme un bébé ? 😢",
        "Snack bizarre que tu kiffes mais personne comprend ? 🍕",
        "Quelle célébrité tu voudrais vraiment rencontrer ?",
        "Ton plus gros regret de cette année ?",
        "Truc que tu collectionnes en secret ?",
        "Surnom embarrassant qu'on t'a donné ?",
        "L'app que tu utilises le plus sur ton tel ?",
        "Dernier gros mensonge à tes parents ?",
        "Personne que t'envies en secret ?",
        "Ton talent caché que peu de gens connaissent ?",
        "Le pire cadeau que t'as jamais reçu ?",
        "Chanson qui te fait danser direct automatiquement ?",
        "Phrase ou mot que tu dis beaucoup trop souvent ?",
        "Dernier rêve bizarre dont tu te souviens ?",
        "Truc que tu fais quand t'es seul(e) chez toi ?",
        "Plat que tu détestes mais tout le monde kiffe ?",
        "Ton excuse préférée pour échapper à un truc ?",
        "Dernier achat complètement inutile ?",
        "Personne avec qui tu parles le plus en messages ?",
        "Souvenir d'enfance le plus gênant ?",
        "Chose que tu prêtes jamais à personne ?",
        "Ton rituel chelou avant de dormir ?",
        "Film que t'as regardé genre 10 fois minimum ?",
        "Ce qui t'énerve le plus chez les gens ?",
        "Ton plat préféré que tu mangerais H24 ?",
        "Dernière fois que t'as eu vraiment la trouille ?",
        "Célébrité que tu trouves overrated ?"
    ],
    
    moyen: [
        "T'as déjà embrassé quelqu'un de ce groupe ? Balance qui 💋",
        "C'est quoi ton plus gros secret que personne sait ? 🤐",
        "T'as déjà été love de quelqu'un ici en secret ? 💘",
        "La pire chose que t'as faite dans ta vie ? 😈",
        "Montre 5 photos random de ta galerie là maintenant 📱",
        "T'as déjà trompé quelqu'un dans une relation ? 💔",
        "Le plus gros mensonge que t'as dit à tes parents ? 👨‍👩‍👦",
        "T'as déjà fouillé le tel de quelqu'un en secret ? 🕵️",
        "Ta recherche Google la plus bizarre récemment ? 🔍",
        "Si tu devais sortir avec quelqu'un du groupe, qui ? 💑",
        "T'as déjà envoyé un message à la mauvaise personne ? Raconte 📨",
        "Ton crush secret dans une autre classe/cercle ?",
        "T'as déjà menti sur ton âge ? Pour quelle raison ? 🎂",
        "Le truc le plus gênant dans ton historique de nav ?",
        "T'as déjà fait semblant d'aimer quelqu'un ? Pourquoi ?",
        "Personne que t'as aimée sans qu'elle le sache jamais ?",
        "Secret que seulement 1-2 personnes connaissent sur toi ?",
        "T'as déjà volé un truc ? C'était quoi ?",
        "Ton pire date/rencard de tous les temps ?",
        "T'as déjà lu les messages privés de quelqu'un ?",
        "Truc embarrassant que tes parents ont découvert ?",
        "T'as déjà menti dans CE jeu ? Sur quelle question ?",
        "Personne dont t'étais jaloux et pourquoi ?",
        "Ton moment le plus gênant en public ?",
        "T'as déjà séché les cours pour un truc fun ?",
        "Secret sur quelqu'un que tu devrais pas connaître ?",
        "T'as déjà fait un truc juste pour impressionner ?",
        "Personne que t'évites et la vraie raison ?",
        "Ton mensonge le plus élaboré de tous les temps ?",
        "T'as déjà ressenti un truc pour l'ex de ton pote ?",
        "Truc que t'as fait à cause de la pression du groupe ?",
        "Personne qui te manque mais tu contactes jamais ?",
        "T'as déjà fait semblant de pas voir quelqu'un ?",
        "Comportement toxique dont t'es conscient ?",
        "T'as déjà lu le journal intime de quelqu'un ?",
        "Chose que tu ferais si personne le savait jamais ?",
        "T'as déjà fake d'être malade pour éviter un truc ?",
        "Personne que t'as blessée et tu regrettes ?",
        "Ton habitude bizarre que tu caches à tout le monde ?",
        "T'as déjà menti pour protéger quelqu'un ?"
    ],
    
    hard: [
        "Lis ton DERNIER échange COMPLET avec ton crush devant nous 💬",
        "Montre tes 15 dernières photos de galerie sans tricher 📸",
        "Raconte TOUT sur le truc illégal que t'as fait 👮",
        "Décris ton fantasme le plus secret en détails 🙈",
        "T'as eu des sentiments pour 2 personnes en même temps ? Qui ? 💔💔",
        "Raconte le truc le plus gênant que tes parents ont découvert 😱",
        "Décris ton PIRE rencard avec TOUS les détails 💀",
        "Révèle ton secret le plus dark que personne connaît 🌑",
        "Montre ton historique de navigation complet d'aujourd'hui 📱",
        "Pendant combien de temps t'as stalké ton ex ? Avoue tout 👀",
        "Montre le message le plus embarrassant que t'as envoyé",
        "Sur quelle question t'as menti dans CE jeu là ? 🎭",
        "Quelle personne du groupe t'évites vraiment ? Pourquoi ?",
        "Décris une pensée bizarre sur quelqu'un d'interdit 🚫",
        "Révèle un secret de quelqu'un d'autre que tu connais 🤫",
        "Lis tes 30 derniers messages avec n'importe qui",
        "Avoue un truc sur toi que personne devrait savoir",
        "Raconte le moment où t'as trahi la confiance de quelqu'un",
        "Révèle une pensée sexuelle embarrassante que t'as eue",
        "Montre tes conversations archivées et explique pourquoi",
        "Avoue le truc le plus horrible que t'as fait par colère",
        "Révèle le crush que tu caches depuis longtemps",
        "Raconte le mensonge le plus destructeur que t'as dit",
        "Montre tes notes/mémos secrets sur ton tel",
        "Avoue un truc que t'as fait et jamais avoué",
        "Révèle un fantasme sur quelqu'un de ce groupe",
        "Raconte le moment le plus humiliant de toute ta vie",
        "Montre tes apps cachées/dossiers secrets du tel",
        "Avoue quelque chose que t'as volé et jamais rendu",
        "Révèle une pensée méchante récurrente sur quelqu'un",
        "Raconte quand t'as blessé quelqu'un exprès",
        "Montre tes recherches sur les réseaux sociaux récentes",
        "Avoue une addiction embarrassante que tu caches",
        "Révèle un secret de famille que tu devrais pas dire",
        "Raconte un truc sexuel embarrassant de ton passé",
        "Montre la dernière personne que t'as stalkée + pourquoi",
        "Avoue une pensée sombre que t'as eue",
        "Révèle une obsession bizarre que t'as",
        "Raconte quand t'as manipulé quelqu'un volontairement",
        "Avoue le mensonge que tu maintiens depuis le plus longtemps"
    ]
};

// 👥 DÉFIS DE GROUPE MODERNES
const defisGroupe = [
    "📸 Tout le monde balance son écran d'accueil MAINTENANT sans triche",
    "🗳️ Votez en secret qui est le/la plus drôle du groupe",
    "🔄 Tout le monde change sa pp en même temps genre synchronisé",
    "💬 Chaîne de compliments, chacun complimente le suivant",
    "⚡ Chacun pose UNE question embarrassante à son voisin GO",
    "🎭 Le bot choisit quelqu'un qui devient roi pendant 10 min",
    "😂 Battle de blagues, la meilleure gagne vote du groupe",
    "🎲 Chacun écrit un secret anonyme, le bot en balance un random",
    "📱 Tout le monde envoie son dernier screenshot SANS exception",
    "🎤 Karaoké géant, tout le monde chante la même chanson en vocal",
    "🎯 Le bot tire 3 personnes : Facile → Moyen → Hard cascade",
    "💭 Confessions anonymes, écrivez au bot il partage",
    "🔥 Hot seat : personne random doit répondre à 7 questions du groupe",
    "🎬 Chacun imite un autre membre en vocal ou vidéo",
    "🏃 50 squats ENSEMBLE et tout le monde envoie la preuve",
    "🎨 Dessinez un membre du groupe, postez, on devine qui",
    "📝 Histoire collaborative, chacun écrit une phrase on crée un délire",
    "🎪 Tout le monde montre son talent caché en 30 secondes",
    "🎯 Mission commune : accomplissez un truc ensemble en 30min",
    "💥 Bombe : passez-la, celui qui l'a dans 2min perd",
    "🎯 Devinez un nombre entre 1-100, le plus proche gagne",
    "🎭 Jouez une scène random ensemble en impro totale",
    "📊 Sondage sur une question controversée, débat après",
    "🎪 Chacun fait un trick physique et filme",
    "🎨 Créez un meme sur un membre du groupe collectivement",
    "📢 Chacun annonce un truc faux dramatique genre 'j'arrête les études'",
    "🎬 Inventez une histoire embarrassante sur un membre",
    "🎯 Chacun a 60 secondes pour faire un défi max",
    "💡 Brainstorm un projet complètement fou pour le groupe",
    "🎪 Spectacle de groupe improvisé de 2 minutes minimum",
    "📸 Tout le monde prend la même pose bizarre en photo de profil",
    "🎭 Jouez des personnages différents pendant 10 min dans le groupe",
    "🎨 Créez une œuvre d'art collective digitale ensemble",
    "📝 Écrivez un poème ligne par ligne chacun votre tour",
    "🎪 Performance de danse/chanson synchronisée du groupe",
    "🎯 Mission : accomplissez quelque chose ensemble en 30 min",
    "💬 Débattez sur un sujet random pendant 5 minutes",
    "🎬 Tournez un mini clip ensemble genre viral",
    "🎪 Défi physique que tout le monde doit relever",
    "📊 Quiz du groupe, celui qui a le meilleur score gagne"
];

// 💬 ROASTS & COMPLIMENTS MODERNES
const roasts = [
    "T'es tellement fauché que tu regardes les pubs YouTube comme du Netflix 💀",
    "Frère tu ressembles à une photo prise avec un Nokia 3310",
    "T'es la raison pour laquelle les shampooings ont des instructions détaillées 😭",
    "Si les excuses étaient des personnes, tu serais une conférence de 3h",
    "Mon gars tu perds à Pierre-Papier-Ciseaux contre toi-même",
    "Même Siri fait semblant de pas t'entendre quand tu parles",
    "Tu mets 'vu' et tu réponds 3 semaines après avec juste 'mdr' 💀",
    "T'es la pub de 30s non-skippable de la vraie vie bro",
    "Tu cours comme si tu chargeais une page Internet en 1999",
    "T'es le contact 'Peut-être' dans le tel de TOUT LE MONDE",
    "Tu danses comme si le WiFi laguait en temps réel frr",
    "T'es tellement en retard que tu pourrais organiser ta propre fête d'anniversaire en janvier",
    "Ta vie amoureuse ressemble à mes notes en maths... inexistante",
    "Tu prends plus de temps à te préparer que Rome à se construire",
    "T'es la raison pour laquelle les aliens visitent pas la Terre",
    "Ton sens de l'orientation est aussi bon qu'une boussole cassée",
    "Tu chantes comme si tu essayais de réveiller les morts pour les re-tuer",
    "T'es tellement lent que les escargots te dépassent en rigolant",
    "Ta cuisine est classée arme de destruction massive par l'ONU",
    "Mon reuf t'es la preuve que l'évolution peut aller à l'envers",
    "Ton humour est aussi sec que le Sahara en pleine canicule",
    "Tu mens tellement mal que Pinocchio semble crédible à côté de toi",
    "T'es tellement distrait que tu oublies ce que tu oublies",
    "Ton style vestimentaire crie au secours silencieusement",
    "T'es l'équivalent humain d'un lundi matin pluvieux",
    "Ta ponctualité est aussi légendaire que les licornes",
    "Tu parles tellement que même les perroquets prennent des notes",
"T'es tellement maladroit que la gravité te déteste personnellement",
    "Ton talent culinaire ferait pleurer Gordon Ramsay... de désespoir",
    "T'es la raison pour laquelle les modes d'emploi existent en 47 langues"
];

const compliments = [
    "Frr t'es tellement incroyable que même ton ombre refuse de te quitter ☀️",
    "Si t'étais un Pokemon tu serais un shiny légendaire avec des stats parfaites 💯",
    "T'es le genre de personne pour qui les chiens abandonnent leurs maîtres",
    "Ton sourire pourrait littéralement résoudre la crise énergétique mondiale",
    "T'es tellement stylé que la glace te demande des conseils de vie",
    "Si la gentillesse était un crime tu serais en perpétuité sans libération",
    "T'es la notification que tout le monde est heureux de recevoir",
    "Ton énergie positive est plus contagieuse que tous les virus réunis",
    "T'es le genre de personne qui rend les lundis matins supportables",
    "Si t'étais une chanson tu serais #1 dans toutes les playlists mondiales",
    "T'es comme le WiFi gratuit illimité : tout le monde t'adore direct",
    "Ton rire est littéralement la meilleure musique jamais composée",
    "Tu illumines une pièce juste en y entrant comme une ampoule LED premium",
    "T'es le chef-d'œuvre que même le Louvre voudrait exposer",
    "Ta présence améliore n'importe quelle situation instantanément",
    "T'es le combo parfait : beauté intérieure + extérieure + personnalité",
    "Tu rends le monde meilleur juste en existant dedans",
    "T'es le genre de personne qui restaure la foi en l'humanité",
    "Ton intelligence n'a d'égale que ta gentillesse c'est rare",
    "T'es littéralement l'ami(e) que tout le monde rêve d'avoir",
    "Tu as ce don naturel de rendre les autres heureux sans effort",
    "T'es la preuve vivante que la perfection existe vraiment",
    "Ta loyauté est plus solide qu'un diamant indestructible",
    "T'es inspirant(e) sans même essayer de l'être c'est ouf",
    "Ton cœur est grand comme l'océan Pacifique entier",
    "T'es le genre de personne qui laisse une empreinte positive durable",
    "Tu as cette aura spéciale que très peu de gens possèdent",
    "T'es l'équilibre parfait entre force et douceur",
    "Ton authenticité est rafraîchissante dans ce monde de faux-semblants",
    "T'es un trésor que ceux qui te connaissent chérissent vraiment"
];

// 🔮 RÉPONSES 8BALL AVEC PERSONNALITÉ
const ball8 = [
    "Oui frr absolument aucun doute là-dessus ✅",
    "C'est certain à 100% je te le garantis 💯",
    "Sans l'ombre d'une hésitation OUI !",
    "Les étoiles et le cosmos disent tous que oui 🔮",
    "Très très probable genre presque sûr 🤔",
    "Peut-être bien peut-être pas... c'est flou là 🤷",
    "Concentre-toi mieux et redemande dans 5 min ⏳",
    "Je peux pas te dire maintenant c'est compliqué 🤐",
    "Franchement compte pas trop dessus mon gars 😬",
    "Mes sources magiques disent clairement NON 🚫",
    "Peu probable désolé de te décevoir 📉",
    "Non franchement laisse tomber cette idée 😕",
    "Absolument PAS n'y pense même plus ! ❌",
    "Dans tes rêves peut-être mais pas IRL 💭",
    "Demande plutôt à ta mère elle saura mieux 👩",
    "Les signes sont mauvais vraiment très mauvais ⚠️",
    "C'est possible mais vraiment improbable 📊",
    "Réessaye quand tu seras plus mature mentalement 🧠",
    "La boule magique a crashé en traitant ta question 💥",
    "Réponse trop dangereuse à révéler maintenant 🚨"
];

// 💾 DONNÉES AVEC PERSONNAL
    